# -*- coding: utf-8 -*-
"""Week4Ques1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1POiU1j2kdrSwfTvRTcrkvkcO3UHw3AmV
"""

import torch

def self_loops(adj):
  num_nodes=adj.shape[0]
  identity=torch.eye(num_nodes)
  return adj + identity

def normalize(adj):
    degree = adj.sum(dim=1, keepdim=True)
    degree = degree.clamp(min=1)
    return adj / degree

def message_passing(adj, node_features):
    adj_with_self_loops = self_loops(adj)
    normalized_adj = normalize(adj_with_self_loops)
    updated_features = normalized_adj @ node_features
    return updated_features

def main():
    adj = torch.tensor([
        [0, 1, 1, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 1],
        [0, 1, 1, 0],
    ], dtype=torch.float32)

    node_features = torch.tensor([
        [1.0, 0.0],  #node 0
        [0.0, 1.0],  #node 1
        [1.0, 1.0],  #node 2
        [0.0, 0.0],  #node 3
    ])

    print("Original node features:")
    print(node_features)

    updated_features = message_passing(adj, node_features)

    print("\nUpdated node features after one message passing step:")
    print(updated_features)


if __name__ == "__main__":
    main()